
<?php
/** @var \Magenest\OrderManager\Block\Address\Edit $_data */
$_data   = $this->getAddress();
if($block->getType() == 'billing') {
    $id = $_data['billing_address_id'];
    $address = $_data->getBillingAddress()->getData();
}
else{
    $id = $_data['shipping_address_id'];
    $address =$_data->getShippingAddress()->getData();
}

$firstName   = $address['firstname'];
$lastName    = $address['lastname'];
$company     = $address['company'];
$telephone   = $address['telephone'];
$fax         = $address['fax'];
$street      = $address['street'];
$city        = $address['city'];
$region      = $address['region'];
$country_id  = $address['country_id'];
$postcode    = $address['postcode'];
?>

<form class="form-address-edit"  method="post" id="form-validate" enctype="multipart/form-data"
      action="<?php echo $block->getBaseUrl()?>"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span></legend><br>
        <div class="field addressid " style="display: none">
            <label class="label" for="addressid"><span><?php /* @escapeNotVerified */ echo __('Address Id') ?></span></label>
            <div class="control">
                <input type="text" name="addressid" id="addressid" title="<?php /* @escapeNotVerified */
                echo __('Address Id') ?>" value="<?php echo $id ?>"   >
            </div>
        </div>
        <div class="field firstname required">
            <label class="label" for="firstname"><span><?php /* @escapeNotVerified */ echo __('First Name') ?></span></label>
            <div class="control">
                <input type="text" name="firstname" id="firstname" title="<?php /* @escapeNotVerified */
                echo __('First Name') ?>" value="<?php echo $firstName ?>"  class="input-text-firstname" >
            </div>
        </div>
        <div class="field lastname required">
            <label class="label" for="lastname"><span><?php /* @escapeNotVerified */ echo __('Last Name') ?></span></label>
            <div class="control">
                <input type="text" name="lastname" id="lastname" title="<?php /* @escapeNotVerified */
                echo __('Last Name') ?>" value="<?php echo $lastName?>"  class="input-text-lastname" >
            </div>
        </div>
        <div class="field company">
            <label class="label" for="company"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
            <div class="control">
                <input type="text" name="company" id="company" title="<?php /* @escapeNotVerified */
                echo __('Company') ?>" value="<?php echo $company ?>" class="input-text-company">
            </div>
        </div>
        <div class="field telephone required">
            <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
            <div class="control">
                <input type="text" name="telephone" id="telephone" title="<?php /* @escapeNotVerified */
                echo __('Phone Number') ?>" value="<?php echo $telephone?>"  class="input-text-telephone" >
            </div>
        </div>
        <div class="field fax">
            <label class="label" for="fax"><span><?php /* @escapeNotVerified */ echo __('Fax') ?></span></label>
            <div class="control">
                <input type="text" name="fax" id="fax" title="<?php /* @escapeNotVerified */
                echo __('fax') ?>" value="<?php echo $fax ?>"  class="input-text-fax" >
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></legend><br>
        <div class="field street required">
            <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
            <div class="control">
                <input type="text" name="street" value="<?php echo $street?>" title="<?php /* @escapeNotVerified */
                echo __('Street Address') ?>" id="street_1" class="input-text-street"  />
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
            <div class="control">
                <input type="text" name="city" value="<?php echo $city ?>" title="<?php /* @escapeNotVerified */
                echo __('City') ?>" class="input-text-city " id="city">
            </div>
        </div>
        <div class="field region">
            <label class="label" for="region_id"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
            <div class="control">
                <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>"
                        class="validate-select" <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegionBilling()) ?>"
                       title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>"
                       class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"
                    <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>

        <div class="field zip">
            <label class="label" for="zip"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
            <div class="control">
                <input type="text" name="postcode" value="<?php echo $postcode ?>" title="<?php /* @escapeNotVerified */
                echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international
                <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
            <div class="control">
                <?php echo $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <?php if(!empty($block->getType() == 'billing')): ?>
        <?php if(!empty($block->getShippingAddress())): ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing"  class="checkbox">
                <label class="label" for="primary_billing"><span><?php /* @escapeNotVerified */
                        echo __('Use as shipping address') ?></span></label>
            </div>
        <?php endif; ?>
        <?php endif; ?>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-address"
                    title="<?php /* @escapeNotVerified */ echo __('Save Address') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Save ') ?></span>
            </button>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
