<?php
/**
 * Copyright © 2015 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @category  Magenest
 */
?>
<?php
/**
 * Copyright © 2015 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 *
 * Magenest_Ticket extension
 * NOTICE OF LICENSE
 *
 * @category  Magenest
 * @package   Magenest_Ticket
 * @author ThaoPV <thaopw@gmail.com>
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magenest\OrderManager\Block\Order\History */ ?>

<?php $_orders = $block->getOrderInfo();
?>
<?php echo $block->getChildHtml('info');?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper ordermanager-orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('My Order') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Order #') ?></th>
                <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status Order') ?></th>
                <th scope="col" class="col check"><?php /* @escapeNotVerified */ echo __('Censorship') ?></th>
                <th scope="col" class="col create"><?php /* @escapeNotVerified */ echo __('Create At') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var \Magenest\Ticket\Model\Ticket|\Magenest\Ticket\Model\Event $_ticket */
            foreach ($_orders as $_order): ?>
                <tr>

                    <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id">
                        <?php /* @escapeNotVerified */ echo $orderId = $_order->getOrderId() ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status Order')) ?>" class="col status">
                        <?php /* @escapeNotVerified */ echo $_order->getStatus() ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Censorship')) ?>" class="col check">
                        <?php /* @escapeNotVerified */
                        if($_order->getStatusCheck()=='accept'||$_order->getStatusCheck()=='delete'){
                            echo "accept";
                        }else{
                            echo $_order->getStatusCheck();
                        }
                         ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Create At')) ?>" class="col create">
                        <?php /* @escapeNotVerified */ echo $_order->getCreateAt() ?>
                    </td>

                    <td data-th="<?php echo /* @escapeNotVerified */ $block->escapeHtml(__('Action')) ?>" class="col action">
                        <?php if($_order->getStatusCheck() != 'no accept'): ?>

                        <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($orderId) ?>" class="action view">
                            <span><?php /* @escapeNotVerified */ echo __('View') ?></span>
                        </a>
                        <?php endif;?>
                        <?php if($_order->getStatusCheck() != 'accept' && $_order->getStatusCheck()!='delete'): ?>
                        |
                        <a href="<?php /* @escapeNotVerified */ echo $block->getDeleteUrl($orderId) ?>" class="action delete">
                            <span><?php /* @escapeNotVerified */ echo __('Delete') ?></span>
                        </a>
                        <?php endif;?>
                    </td>

                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php echo count($_orders).' Item(s)' ?>
    <?php if ($block->getPagerHtml()): ?>
        <div class="ordermanager-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have placed no any order edit.'); ?></span></div>
<?php endif ?>
