<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 24/05/2016
 * Time: 15:05
 */
?>
<?php /** @var  $block Magenest\OrderManager\Block\Adminhtml\Order\Edit\Tab\Address */ ?>
<?php
$_billing   = $block->getBillingAddress();
$_shipping   = $block->getShippingAddress();
$order_id   = $block->getOrderId();
?>
<?php if (!empty($_billing) || !empty($_shipping)):?>
    <table class="data-table" data-role="flex-table">
        <thead>
        <tr class="headings">
            <th class="col-billing">
                <span><?php /* @escapeNotVerified */ echo __('Billing Address') ?></span>
                <?php if(!empty($_billing) && $block->getAccept() == 0):?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getCustomBillingUrl($order_id) ?>" class="action view">
                        <span><?php /* @escapeNotVerified */ echo __('Edit') ?></span>
                    </a>
                <?php endif;?>
            </th>
            <th class="col-shipping">
                <span><?php /* @escapeNotVerified */ echo __('Shipping Address') ?></span>
                <?php if(!empty($_shipping) && $block->getAccept() == 0):?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getCustomShippingUrl($order_id) ?>" class="action view">
                        <span><?php /* @escapeNotVerified */ echo __('Edit') ?></span>
                    </a>
                <?php endif;?>
            </th>
        </tr
        </thead>
        <tbody>
        <tr>
            <td data-th="<?php echo $block->escapeHtml(__('Billing Address')) ?>" class="col-billing">
                <?php if(!empty($_billing)):?>
                <?php echo  $_billing['name']; ?>
                </br>
                <?php echo  $_billing['company']; ?>
                </br>
                <?php echo  $_billing['street']; ?>
                </br>
                <?php echo  $_billing['region_info']; ?>
                </br>
                <?php echo  $_billing['country']; ?>
                </br>
                <?php echo  'T: '.$_billing['telephone']; ?>
                <?php else :?>
                <?php echo 'No Change' ?>
                <?php endif;?>

            </td>
            <td data-th="<?php echo $block->escapeHtml(__('Shipping Address')) ?>" class="col-shipping">
                <?php if(!empty($_shipping)):?>

               <?php echo  $_shipping['name']; ?>
                </br>
                <?php echo  $_shipping['company']; ?>
                </br>
                <?php echo  $_shipping['street']; ?>
                </br>
                <?php echo  $_shipping['region_info']; ?>
                </br>
                <?php echo  $_shipping['country']; ?>
                </br>
                <?php echo  'T: '.$_shipping['telephone']; ?>

                 <?php else :?>
                <?php echo 'No Change' ?>
                <?php endif;?>
            </td>
        </tr>
        </tbody>
    </table>
<?php endif; ?>